<?php

return [
    // Header Section
    'header' => [
        'order_prefix' => 'Order #',
        'total_label'  => 'Total:',
    ],

    // Payment Section
    'payment' => [
        'paid_amount_label'   => 'Paid Amount:',
        'update_button'       => 'Update',
        'cancel_button'       => 'Cancel',
        'paid_label'          => 'Paid:',
        'edit_paid_button'    => 'Edit Paid Amount',
        'error_paid_message'  => 'The paid amount field is required.', // Example, actual validation messages are usually in validation.php
    ],

    // Filter Section
    'filter' => [
        'label'              => 'Filter by Ticket Type:',
        'all_types_option'   => 'All Types',
    ],

    // Tickets Section
    'tickets' => [
        'none_found_header'      => 'No tickets found',
        'none_found_message'     => 'There are no tickets associated with this order.',
        'qr_not_available'       => "QR Code\nNot Available", // Using \n for the line break, adjust rendering if needed
        'card_title_prefix'      => 'Ticket #',
        'unknown_type'           => 'Unknown Type',
        'status_label'           => 'Status:',
        'status_active'          => 'Active',
        'status_inactive'        => 'Inactive',
        'select_checkbox_checked'   => 'Selected',
        'select_checkbox_unchecked' => 'Select',
        'none_match_filter'      => 'No tickets match the selected filter.',
        'all_hidden_by_filter'   => 'All available tickets are currently hidden by the filter.', // This specific message might not be easily translatable if generated by component logic, but providing a key.
        'image_alt_prefix'       => 'QR Code for Ticket', // For QR code image alt text
        'image_not_embedded'     => 'Ticket image could not be embedded.', // For the fallback text in image display
        'image_not_found'        => 'Ticket image could not be generated or found.',
        'title'                  => 'Your Tickets:',
    ],

    // Order Actions Section
    'actions' => [
        'group_title'               => 'Order Actions',
        'download_selected_button'  => 'Download Selected',
        'download_all_button'       => 'Download All',
        'activate_selected_button'  => 'Activate Selected',
        'deactivate_selected_button'=> 'Deactivate Selected',
    ],
];
